name: CD Frontend

on:
  workflow_dispatch:
  workflow_run:
    workflows: [CI Frontend]
    types: [completed]
    branches: [main]

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: sws2apps/render-deployment@v2.0.0
        with:
          serviceId: ${{ secrets.RENDER_FRONTEND_SERVICE_ID }}
          apiKey: ${{ secrets.RENDER_API_KEY }}
