name: CI Mobile App

on:
  push:
    branches: [main]
    paths:
      - 'mobileapp/**'
  pull_request:
    branches: [main]
    paths:
      - 'mobileapp/**'

jobs:
  mobileapp:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mobileapp
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew :composeApp:jvmTest
